sudo: false

language: python

python:
  - 2.7
  - 3.5

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
   # download/install pythonocc from DLR-SC channel
  - conda config --add channels https://conda.anaconda.org/dlr-sc
  # install everything required to build the receipe
  - conda install pythonocc-core


script:
  - python setup.py build install
  - cd test  
  - python occutils_test.py

branches:
  only:
    - master
    - /^review/
